version: '3'
services:
  db:
    image: postgres:alpine
    container_name: RememberMe-db
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: ''
    ports:
      - 5432:5432

  build_db:
    build: ./database
    container_name: RememberMe-build-db
    environment:
      NODE_ENV: 'development'
    volumes:
      - ./database:/app
      - /app/node_modules
    depends_on:
      - db

  server:
    build: ./server
    container_name: RememberMe-server
    environment:
      DATABASE_URL: 'postgres://postgres:@db:5432/postgres'
      NODE_ENV: 'development'
      DYNO: 'web.1'
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
    ports:
      - 3000:3000
    command: npm run dev
